// changed-quips.js
export const CHANGED_QUIPS = {
  low: [
    "same firmware, different day.",
    "changed? nah—just rotated slightly.",
    "still default settings.",
    "character development: buffering.",
    "the arc is not arcing.",
    "minor patch notes. no major updates.",
    "same vibes, new timestamp.",
    "growth detected: microscopic.",
    "they evolved into… the same form.",
    "new hoodie, same person.",
    "they updated everything except the attitude.",
    "still in their original era.",
    "development stalled at 1%.",
    "same plot, same twist, same ending.",
    "not changed—merely rebranded.",
    "still running on windows 98 emotionally.",
    "they installed updates then hit ‘remind me tomorrow’.",
    "same chaos, slightly louder.",
    "the glow-up is pending approval.",
    "still allergic to growth.",
    "they took a step forward and respawned.",
    "same person, different font.",
    "their redemption arc got canceled.",
    "no notes. still them.",
    "they changed like a freezer’s weather.",
    "the ‘new me’ is a subscription they forgot to pay.",
    "barely changed—just better posture.",
    "same energy, just more confident about it.",
    "growth status: still loading.",
    "they changed like a USB: took 3 tries, same result."
  ],

  mid: [
    "they’re better… but don’t tempt them.",
    "character development with a few bugs.",
    "new habits, old instincts.",
    "half glow-up, half ‘don’t test me.’",
    "progress confirmed—relapse possible.",
    "improved version, same DLC.",
    "they learned lessons but skipped homework.",
    "better decisions, questionable impulses.",
    "they upgraded the software, kept the same tabs open.",
    "new arc, familiar soundtrack.",
    "reformed-ish.",
    "they changed enough to surprise the group chat.",
    "growth unlocked, ego still equipped.",
    "better vibes, same sarcasm.",
    "they’re trying, and it’s showing.",
    "stronger boundaries, weaker patience.",
    "they don’t start drama… as much.",
    "new mindset, old reflexes.",
    "they’re in their ‘work in progress’ era.",
    "they grew… but kept the receipts.",
    "they changed—still side-eyes nonsense though.",
    "progress is progress, okay?",
    "they upgraded morals, left the attitude.",
    "they healed a little, still petty on weekends.",
    "they’re doing better, but keep a backup plan for chaos.",
    "they’re mostly changed—just not fully cooked yet.",
    "they turned the page… but bookmarked the old chapter.",
    "they’re leveling up with occasional misclicks.",
    "they’re improved, still spicy.",
    "growth with side quests."
  ],

  high: [
    "that’s a whole new person, respectfully.",
    "rewritten. reforged. rebooted.",
    "final evolution energy.",
    "new era unlocked.",
    "emotional firmware updated successfully.",
    "they did the work and the reps.",
    "the old them would be shook.",
    "they’re different-different.",
    "glow-up so loud it has subtitles.",
    "they left the old version in the archives.",
    "growth went crazy.",
    "they healed, leveled up, and logged back in.",
    "main character arc activated.",
    "they went from side quest to final boss (in a good way).",
    "factory reset actually worked.",
    "that’s 4K Ultra HD character growth.",
    "they turned the page and burned the old book.",
    "legendary tier unlocked.",
    "they found peace and kept the drip.",
    "they’re living proof people can upgrade.",
    "they changed like rent prices: aggressively.",
    "they evolved past everyone’s expectations.",
    "their redemption arc hit the season finale.",
    "the past is confused.",
    "they’re running on healthy settings now.",
    "they got upgraded to premium human.",
    "they’re the glow-up blueprint.",
    "they changed so much even autocorrect respects them.",
    "they’re in their ‘I got my life together’ arc.",
    "transformation sequence complete."
  ]
};
