// faction-text.js
// Clean, ASCII-safe strings. Short and punchy for Twitch chat.

// ===========================
// 50 LOSER ROASTS PER FACTION
// ===========================
export const DUEL_ROASTS = {
  jedi: [
    "Your lightsaber was on 'sleep mode.'",
    "Meditated so hard you forgot to block.",
    "Missed every swing like it was choreography.",
    "The Force tried to help and said 'nvm.'",
    "Your calm turned into a full system crash.",
    "Read the whole code of conduct and still caught these hands.",
    "Should’ve parried… or prayed.",
    "You brought wisdom to a fistfight.",
    "Council called — they want their L back.",
    "That was less 'deflect' and more 'accept.'",
    "Inner peace? More like inner peas.",
    "You blocked like a screen door in a hurricane.",
    "Saw the future, chose the worst timeline.",
    "You used Force Push on yourself.",
    "‘Use the Force’ — you used the Force Quit.",
    "Yoda says: ‘Do not.’ You did not.",
    "The High Ground filed for divorce.",
    "Your robe has more holes than your defense.",
    "Even the training droids are giggling.",
    "Mind tricked yourself into losing.",
    "Lightsaber safety was ON. Respectful, but tragic.",
    "Brought a proverb to a beatdown.",
    "You tried patience; they tried violence.",
    "Peace was never an option… for your HP bar.",
    "Your serenity got stun-locked.",
    "Healer main energy — wrong lobby.",
    "That stance said 'yoga,' not 'duel.'",
    "Took the High Ground and the low score.",
    "Force Ghost pre-ordered.",
    "You parried air like it owed you money.",
    "Meditation timer expired mid-fight.",
    "Zen mode disabled by reality.",
    "Your saber hum sounded like a dial-up tone.",
    "You reflected zero and collected all.",
    "Jedi archives recorded a new comedy entry.",
    "Tried to negotiate with a haymaker.",
    "Diplomacy checked: critical fail.",
    "You rolled 'Serenity' while they rolled 'Spin2Win.'",
    "Got outplayed by basic footwork.",
    "The Force said 'brb' and never returned.",
    "Your ki-adi-Mundi? More like ki-adi-Mundy.",
    "Saber form: PowerPoint.",
    "Even a Padawan would’ve dodged that.",
    "You tried to stun with wisdom. It didn’t land.",
    "Blue blade, blue screen.",
    "Sent to timeout by a Sith intern.",
    "Telegraphed every move like a newsletter.",
    "Your mind was calm; your KD was not.",
    "Balance achieved: you vs. floor.",
    "Master? Today you mastered the art of L."
  ],
  sith: [
    "Unlimited power? Limited aim.",
    "All that rage, zero footwork.",
    "Choked… on your own monologue.",
    "Anger management called — you failed the practical.",
    "You yelled and then slipped. Cinema.",
    "Red saber, red flags, red KO.",
    "Swing harder? Maybe swing smarter.",
    "Lightning fizzled like a cheap sparkler.",
    "Intimidation check: rolled a 1.",
    "Roared so loud you missed the parry.",
    "Edgelord vibes, butter-knife results.",
    "Cape flow immaculate; technique tragic.",
    "You farmed hate, forgot defense.",
    "Your fury got kited like a dad at a park.",
    "Tried a finisher at full HP. Bold.",
    "Got parried by a proverb.",
    "‘Do it’ — you didn’t.",
    "Menace meter high; accuracy at zero.",
    "Your duel became a TED Talk.",
    "Went for style points, scored none.",
    "You Force-pushed the air dramatically.",
    "Breathing louder than your saber swings.",
    "Villain arc skipped the training montage.",
    "Footwork courtesy of a Roomba.",
    "Screamed, slipped, submitted.",
    "That wasn’t a clash; that was a cry.",
    "Hate fueled you straight into a wall.",
    "Darth Try-Again.",
    "Even your theme music facepalmed.",
    "Got reflected like a bad take.",
    "You brought a monologue to a speedrun.",
    "All caps, no damage.",
    "You rolled 'crit miss' on menace.",
    "The Dark Side refunded your deposit.",
    "Your drip outperformed your DPS.",
    "Lightning? More like static cling.",
    "Raised your voice, lowered your health.",
    "You were the final boss of nothing.",
    "Sith laundry day: washed, folded, defeated.",
    "Menacing entrance, meek exit.",
    "Fueled by rage, stalled by geometry.",
    "Threw hands; received feedback.",
    "Tried to force-choke the scoreboard.",
    "Your aura screamed; your saber whispered.",
    "Ego tanked. So did everything else.",
    "Even the stormtroopers landed more hits.",
    "Your cape did two spins; you did zero.",
    "Dark Side said 'suboptimal play detected.'",
    "Darth Fumble has entered the canon."
  ],
  gray: [
    "Balanced yourself right off the win.",
    "Sat on the fence, got splinters and an L.",
    "You tried harmony; they tried hands.",
    "Neutral until the knock-out — efficient.",
    "You balanced both options: miss and whiff.",
    "Gray area? More like gray out.",
    "Meditated mid-swing — bold choice.",
    "Neither light nor dark — just dim.",
    "You picked both sides and got neither.",
    "Peace and passion canceled each other — so did you.",
    "Even your saber color shrugged.",
    "You rolled 'maybe,' they rolled 'delete.'",
    "Tried to adapt, forgot to attack.",
    "Your versatility had commitment issues.",
    "Sat between stars and shadow — and the floor.",
    "Both/and energy, neither/win result.",
    "You parried the concept of trying.",
    "Balanced, then toppled.",
    "Played both sides and lost to one.",
    "Gray Jedi? Gray jelly.",
    "You toggled forms like a light switch in a storm.",
    "Ambidextrous L.",
    "Master of nuance, victim of knuckles.",
    "Your destiny said 'it depends.'",
    "You countered vibes, not strikes.",
    "Middle path led to the exit screen.",
    "You negotiated with physics and lost.",
    "Adapted into defeat.",
    "Your doctrine: 'we'll see.' We saw.",
    "Schrödinger’s win — opened the box, it was an L.",
    "Balanced perfectly… on the edge of failure.",
    "You flow-charted yourself into the floor.",
    "Flexible spine, fragile ego.",
    "Parried light, dodged dark, ate fist.",
    "Your neutral stance was neutralized.",
    "Even your saber hummed 'meh.'",
    "Jack of all trades, master of Ls.",
    "Two paths diverged; you tripped in the middle.",
    "You changed forms; they changed your mind.",
    "Equilibrium reached: zero points.",
    "Neutral game? Neutralized.",
    "Your philosophy was heavy; your guard was light.",
    "Balanced take. Unbalanced jaw.",
    "You hedged and got wedged.",
    "Mixed build, mixed results, fixed defeat.",
    "Tried to counter everything, countered nothing.",
    "You dodged commitment like attacks.",
    "The Force said 'pick a lane.'",
    "Both sides denied your refund.",
    "Center stage exit, pursued by L."
  ]
};

// ===========================
// 30 RALLY LINES PER FACTION
// ===========================
export const RALLY_LINES = {
  jedi: [
    "stands in calm focus, fortifying the Jedi Order. +1 Jedi.",
    "breathes in serenity; the Council nods. +1 Jedi.",
    "channels peace into purpose. +1 Jedi.",
    "opens the Archives and the mind. +1 Jedi.",
    "anchors the High Ground with quiet conviction. +1 Jedi.",
    "becomes the still point in a spinning world. +1 Jedi.",
    "lights the blue path forward. +1 Jedi.",
    "deflects doubt, embraces duty. +1 Jedi.",
    "listens to the Force, then acts. +1 Jedi.",
    "guards hope like a temple flame. +1 Jedi.",
    "tempers steel with wisdom. +1 Jedi.",
    "binds the Order together. +1 Jedi.",
    "moves as one with the Force. +1 Jedi.",
    "turns chaos into clarity. +1 Jedi.",
    "holds the line without hate. +1 Jedi.",
    "answers fear with focus. +1 Jedi.",
    "chooses patience over panic. +1 Jedi.",
    "guides without grabbing. +1 Jedi.",
    "finds light in the static. +1 Jedi.",
    "keeps the saber steady, heart steadier. +1 Jedi.",
    "is the breath between storms. +1 Jedi.",
    "sets the tone, not the fire. +1 Jedi.",
    "resolves the conflict within. +1 Jedi.",
    "guards the weak, steadies the brave. +1 Jedi.",
    "refuses the easy path. +1 Jedi.",
    "drinks water and minds business. +1 Jedi.",
    "hears the Force whisper 'nice.' +1 Jedi.",
    "finds balance without breaking. +1 Jedi.",
    "turns doubt to duty. +1 Jedi.",
    "brings the glow, not the smoke. +1 Jedi."
  ],
  sith: [
    "channels raw fury; the Dark Side surges. +1 Sith.",
    "lets anger sharpen every edge. +1 Sith.",
    "grins as power answers. +1 Sith.",
    "feeds the fire on purpose. +1 Sith.",
    "moves like a blade thrown by fate. +1 Sith.",
    "turns spite into speed. +1 Sith.",
    "drinks chaos like espresso. +1 Sith.",
    "promises pain and delivers. +1 Sith.",
    "breaks limits, then the meter. +1 Sith.",
    "lets the hate flow — responsibly. +1 Sith.",
    "hunts the high ground. +1 Sith.",
    "hears thunder and laughs back. +1 Sith.",
    "forges will into weapon. +1 Sith.",
    "smiles; alarms go off. +1 Sith.",
    "answers peace with pressure. +1 Sith.",
    "turns fear into fuel. +1 Sith.",
    "cuts the brakes, floors destiny. +1 Sith.",
    "stares down light and squints. +1 Sith.",
    "sharpens the red line. +1 Sith.",
    "orders the storm to march. +1 Sith.",
    "makes menace look easy. +1 Sith.",
    "tightens the grip on fate. +1 Sith.",
    "finds strength in the scorch. +1 Sith.",
    "picks violence and gets change back. +1 Sith.",
    "lets ambition eat breakfast. +1 Sith.",
    "speaks softly, swings loudly. +1 Sith.",
    "refuses mercy, demands victory. +1 Sith.",
    "writes threats in calligraphy. +1 Sith.",
    "turns a glare into gravity. +1 Sith.",
    "puts the 'ow' in power. +1 Sith."
  ],
  gray: [
    "bends the balance to their will. +1 Assist.",
    "walks the middle, nudges the meter. +1 Assist.",
    "chooses a side today — maybe. +1 Assist.",
    "tips the scales with a fingertip. +1 Assist.",
    "helps without pledging. +1 Assist.",
    "threads the needle between extremes. +1 Assist.",
    "does diplomacy with results. +1 Assist.",
    "balances, then shoves. +1 Assist.",
    "calls it like it is, then acts. +1 Assist.",
    "sees angles the factions miss. +1 Assist.",
    "brings leverage, not loyalty. +1 Assist.",
    "keeps receipts; spends them wisely. +1 Assist.",
    "favors the fun side today. +1 Assist.",
    "plays both teams like a DJ. +1 Assist.",
    "applies pressure surgically. +1 Assist.",
    "puts weight where it hurts. +1 Assist.",
    "tosses a coin; chooses a cause. +1 Assist.",
    "keeps the balance interesting. +1 Assist.",
    "shifts momentum with style. +1 Assist.",
    "nudges destiny off-center. +1 Assist.",
    "gives exactly enough help. +1 Assist.",
    "is the wild card the war deserves. +1 Assist.",
    "brings gravity to the moment. +1 Assist.",
    "favors whoever’s funnier. +1 Assist.",
    "declares 'I’m with chaos.' +1 Assist.",
    "sticks and moves like strategy. +1 Assist.",
    "tips the beam, winks, leaves. +1 Assist.",
    "chooses side-quests over sides. +1 Assist.",
    "makes balance do a trick. +1 Assist.",
    "keeps fate guessing. +1 Assist."
  ]
};

// ===========================
// 30 BAR EVENTS (with effects)
// Format: { id, text, effect: { jedi: +N, sith: -M } } 
// Positive adds, negative subtracts. Gray is omitted by design here.
// ===========================
export const BAR_EVENTS = [
  { id: "council_decree", text: "Jedi Council issues a calm decree. +3 Jedi.", effect: { jedi: +3, sith: 0 } },
  { id: "inquisitor_raid", text: "Sith Inquisitors raid the cantina. +3 Sith.", effect: { jedi: 0, sith: +3 } },
  { id: "kyber_spill", text: "Kyber crystals resonate through the room. +2 Jedi.", effect: { jedi: +2, sith: 0 } },
  { id: "power_surge", text: "A surge of rage powers the Dark Side. +2 Sith.", effect: { jedi: 0, sith: +2 } },
  { id: "padawan_parade", text: "Padawans inspire the crowd. +1 Jedi.", effect: { jedi: +1, sith: 0 } },
  { id: "sith_rumors", text: "Whispers of fear ripple out. +1 Sith.", effect: { jedi: 0, sith: +1 } },
  { id: "temple_chant", text: "Temple chants steady the spirit. +2 Jedi.", effect: { jedi: +2, sith: 0 } },
  { id: "midnight_menace", text: "Menace o’clock hits the bar. +2 Sith.", effect: { jedi: 0, sith: +2 } },
  { id: "guardian_watch", text: "Jedi Guardians take watch. +2 Jedi.", effect: { jedi: +2, sith: 0 } },
  { id: "saber_throw", text: "A saber flies past the jukebox. +2 Sith.", effect: { jedi: 0, sith: +2 } },
  { id: "force_field", text: "Invisible calm shields the patrons. +1 Jedi.", effect: { jedi: +1, sith: 0 } },
  { id: "fear_wave", text: "A wave of dread chills the room. +1 Sith.", effect: { jedi: 0, sith: +1 } },
  { id: "blue_glow", text: "Blue glows brighten the dance floor. +2 Jedi.", effect: { jedi: +2, sith: 0 } },
  { id: "red_echo", text: "Red echoes rattle the glasses. +2 Sith.", effect: { jedi: 0, sith: +2 } },
  { id: "healer_rounds", text: "Jedi healers patch the vibes. +1 Jedi.", effect: { jedi: +1, sith: 0 } },
  { id: "acolyte_anthem", text: "Acolytes chant in harmony (of chaos). +1 Sith.", effect: { jedi: 0, sith: +1 } },
  { id: "council_vote", text: "Council votes: more patience. +3 Jedi.", effect: { jedi: +3, sith: 0 } },
  { id: "wrath_spike", text: "Wrath spikes like the bass. +3 Sith.", effect: { jedi: 0, sith: +3 } },
  { id: "peace_round", text: "Peace bought a round for the bar. +1 Jedi.", effect: { jedi: +1, sith: 0 } },
  { id: "spite_round", text: "Spite bought two. +1 Sith.", effect: { jedi: 0, sith: +1 } },
  { id: "holocron_open", text: "A holocron hums with calm. +2 Jedi.", effect: { jedi: +2, sith: 0 } },
  { id: "relic_crack", text: "A dark relic cracks with power. +2 Sith.", effect: { jedi: 0, sith: +2 } },
  { id: "guardian_cheer", text: "The crowd chants for the Jedi. +1 Jedi.", effect: { jedi: +1, sith: 0 } },
  { id: "inquisitor_glare", text: "An Inquisitor glares; hearts skip. +1 Sith.", effect: { jedi: 0, sith: +1 } },
  { id: "calm_wave", text: "A calm wave cools tempers. +2 Jedi.", effect: { jedi: +2, sith: 0 } },
  { id: "rage_drum", text: "Drums summon rage from the floor. +2 Sith.", effect: { jedi: 0, sith: +2 } },
  { id: "blue_confetti", text: "Blue confetti cannon — delight achieved. +1 Jedi.", effect: { jedi: +1, sith: 0 } },
  { id: "red_smoke", text: "Red smoke machines hiss. +1 Sith.", effect: { jedi: 0, sith: +1 } },
  { id: "master_arrives", text: "A Jedi Master walks in. +3 Jedi.", effect: { jedi: +3, sith: 0 } },
  { id: "darth_arrives", text: "A Darth walks in. Everyone feels it. +3 Sith.", effect: { jedi: 0, sith: +3 } }
];

// ===========================
// 20 INVASION START QUIPS
// ===========================
export const INVASION_STARTS = [
  "Sirens blare. The Invasion begins — points are doubled!",
  "Shields down! Invasion window open — earn fast, strike faster.",
  "Distortion Event: INVASION. Double gains for all actions.",
  "The cantina doors burst open — it’s Invasion time!",
  "War drums thunder. Invasion has started. Double points now.",
  "Blue and red lights flood the room — double points engage.",
  "Jukebox screams, sabers ignite — Invasion underway.",
  "Council and Cabal clash — Invasion window active.",
  "The bartender ducks — this is not a drill. Invasion!",
  "Gravity tilts. Invasion event: double your swings.",
  "Dark clouds roll in — Invasion multiplier live.",
  "Peace retreats, fury advances — Invasion now.",
  "A holocron cracks open — Invasion has begun.",
  "Sound the alarms — double points for a short time!",
  "The Force surges — Invasion streak active.",
  "From the rafters: ‘INVASION!’ Rack up the score.",
  "The walls glow blue and red — Invasion starts.",
  "Destiny accelerates — seize the Invasion.",
  "The room splits down the middle — Invasion active.",
  "This is the moment — Invasion has entered the chat."
];

// 25 auto-loss quips for challenging D4rth_Distortion
export const D4RTH_ROASTS = [
  "You challenged D4rth Distortion? Bold. Dead, but bold.",
  "The bass dropped, your chances didn’t.",
  "Even the Force took a step back on that one.",
  "D4rth didn’t swing. The fear did the work.",
  "The Dark Side calls that 'self-elimination.'",
  "That’s not courage, that’s career suicide.",
  "You didn’t fight D4rth — you auditioned for defeat.",
  "Even your midi-chlorians noped out.",
  "You blinked, reality corrected your mistake.",
  "D4rth didn’t need a saber — the Wi-Fi drop alone wrecked you.",
  "Thanks for the donation; the Sith ledger appreciates it.",
  "The bar fell silent… again. Another one challenged D4rth.",
  "No hit markers. Just the sound of destiny laughing.",
  "You tried. The universe filed it under 'comedy.'",
  "Your duel request has been automatically denied by reality.",
  "You attacked, D4rth blinked — and you ceased to exist.",
  "D4rth doesn’t fight. He removes problems.",
  "Welcome to the highlight reel of bad ideas.",
  "Achievement unlocked: Regret.",
  "The Sith ledger records another unpaid debt.",
  "Your bravery will be remembered… by no one.",
  "Even your ghost rage-quit.",
  "The crowd yelled 'FATALITY' before it started.",
  "You fought the D4rth, and the D4rth won.",
  "Respectfully: never do that again.",
  "Is you stupid or is you dumb?.",
];
