// hate-quips.js (ESM)
export const HATE_TIERS = [
  {
    name: "low",
    min: 1,
    max: 25,
    lines: [
      "You must be one of those Jedi. Smh couldn’t be me.",
      "That hate is kinda… adorable. Like a kitten hiss.",
      "Light dislike. You’ll survive. Probably.",
      "That’s not hate — that’s mild inconvenience.",
      "Your rage is buffering. Try again later.",
      "Hate level: diet edition. Zero calories.",
      "You’re hating politely. Respectfully unhinged.",
      "That’s a “dang, anyway” level of hate.",
      "You’re not mad, you’re just… disappointed.",
      "That hate wouldn’t scare a droid.",
      "Small hate. Big feelings. Tiny damage.",
      "Your hate is set to ‘vibrate’, not ‘ring’.",
      "You’re throwing shade with a night light.",
      "That hate is whispering, not screaming.",
      "We found the hate… it’s in stealth mode.",
      "You’re hating in lowercase.",
      "Barely a grudge. More like a frown.",
      "Mild hate. Like stepping on one LEGO… with shoes on.",
      "A soft boo. Not even a full heckle.",
      "The Shroud blinked… and went back to sleep."
    ],
  },
  {
    name: "mid",
    min: 26,
    max: 50,
    lines: [
      "Okay okay… we’ve got some spice in that hate.",
      "That’s a solid ‘I don’t rock with you’ rating.",
      "Mid-tier hate: the side-eye is LOCKED in.",
      "You’re hating with intention now. Love that for you.",
      "This is ‘mute them but still watch’ hate.",
      "Your hate just started warming up.",
      "You’re not furious — you’re *firmly annoyed*.",
      "This is the ‘petty with a purpose’ tier.",
      "Not a full villain arc… but the trailer dropped.",
      "The Shroud is leaning forward like 👀",
      "That hate has posture. Straight-backed bitterness.",
      "You’re simmering. A slow cook of disrespect.",
      "Hate level says “don’t ask me for favors.”",
      "This is ‘I remember what you did in 2017’ hate.",
      "Your inner Sith is stretching.",
      "Okay hater… the vibes are aggressively mid.",
      "That hate has receipts but hasn’t posted them yet.",
      "You’re hating on main, but calmly.",
      "A respectable amount of chaos. Noted.",
      "You’re one inconvenience away from popping off."
    ],
  },
  {
    name: "high",
    min: 51,
    max: 75,
    lines: [
      "Okay we sense the hate now — certified hater detected.",
      "That’s real hate. The Shroud is nodding.",
      "Your hate has muscle. It lifts.",
      "This is ‘block and report’ energy.",
      "Your aura just turned maroon and violent.",
      "You’re beefing spiritually at this point.",
      "That hate is loud. Like caps-lock loud.",
      "You’re one speech away from a villain monologue.",
      "Hate level is doing cardio. It’s ACTIVE.",
      "You’re not annoyed — you’re *offended*.",
      "This is the ‘I’m praying on your downfall’ tier. (In Minecraft.)",
      "Your hate has a theme song now.",
      "You’re cooking a grudge like it’s Thanksgiving dinner.",
      "You’re throwing shade with professional accuracy.",
      "That hate has range. Sniper-level petty.",
      "You’re hating with choreography.",
      "This is ‘I remember your username’ hate.",
      "The Shroud is awake and choosing violence.",
      "Your hate just hit a growth spurt.",
      "This is the “we got history” tier."
    ],
  },
  {
    name: "unlimited",
    min: 76,
    max: 100,
    lines: [
      "HATE HATE HATE! ⚡⚡⚡ The Shroud consumes all.",
      "UNLIMITED HATRED ⚡ Palpatine would be proud.",
      "Your hate just bent the timeline. Congrats.",
      "This is generational hate. Bloodline certified.",
      "You’re hating in 4K UHD with surround sound.",
      "Your hate is a whole DLC expansion pack.",
      "That hate could power a small city.",
      "You’re not a hater — you’re the final boss of hate.",
      "The Shroud is chanting your name right now.",
      "This hate has plot armor. It won’t die.",
      "Your hate has a passport. It travels.",
      "You’re hating like rent is due tomorrow.",
      "This is villain-origin-story hate.",
      "Your hate just unlocked a new Force ability.",
      "That’s “I hope your fries are cold” hatred.",
      "Your hate is so strong it needs a cooldown timer.",
      "You’re hating with lightning in your fingertips.",
      "This hate is a straight-up cinematic cutscene.",
      "Your hate woke up and chose war crimes. (In a video game.)",
      "The Shroud has you on speed dial."
    ],
  },
];
