// puff-quips.js (ESM)

export const PUFF_WEEDS = [
  "Shroud Kush",
  "Void Haze",
  "Ember Bloom",
  "Obsidian OG",
  "Crimson Crescent",
  "Distortion Diesel",
  "Nightfall Nectar",
  "Aether Mist",
  "Graveyard Gelato",
  "Starforge Skunk",
  "Hexberry Haze",
  "Ashen Pineapple",
  "Sithberry Sherbet",
  "Blackhole Runtz",
  "Riftwalker Rosin",
  "Cinder Cake",
  "Moonlit Mule",
  "D4rth Mintz",
  "Wraith Cookies",
  "Shadowberry Splash"
];

// Tiered “elevated” quips (20 per tier)
export const PUFF_QUIPS = {
  low: [
    "Elevation detected, but the Shroud is like… ‘meh’.",
    "You’re lightly toasted. Like warm bread energy.",
    "The vibe is gentle. A respectful float.",
    "Barely airborne. You’re on a step stool, not a cloud.",
    "Your aura said “maybe later.”",
    "This is ‘I can still do math’ high.",
    "A mild lift. The Shroud blinked and moved on.",
    "You’re elevated… to the second floor.",
    "Slightly lifted. No flight clearance yet.",
    "This is ‘music sounds 7% better’ territory.",
    "You’re vibing, but responsibly.",
    "The Shroud is stretching, not awakening.",
    "Soft elevation. Like a chill elevator ride.",
    "Your soul is warmed, not launched.",
    "Low orbit. Still within Wi-Fi range.",
    "You’re floatin’, not soaring.",
    "A calm puff. The Realm approves politely.",
    "You’re high-ish. Like ‘nice breeze’ high.",
    "Minimal lift—still legally a person.",
    "The Shroud whispers: ‘cute.’"
  ],
  mid: [
    "Okay okay… you’re hovering now.",
    "Elevation steady. The Realm is nodding like ‘go on’.",
    "You’re in the pocket. Prime vibe altitude.",
    "Mid-tier lift: thoughts are *sparkly* now.",
    "You’re floating with intention. Love that.",
    "This is the ‘deep convo at 2am’ setting.",
    "The Shroud is awake and taking notes.",
    "You’re elevated enough to feel cinematic.",
    "Vibes are immaculate. Gravity is optional.",
    "This puff has you staring at a wall respectfully.",
    "Okay — we’re cooking. Mentally and spiritually.",
    "Mid lift: you’re laughing at loading screens.",
    "You just unlocked ‘philosopher mode’.",
    "Your aura is doing parkour.",
    "The Realm background music just kicked in.",
    "You’re high enough to text ‘yo’ and mean it.",
    "Your brain is in surround sound.",
    "This is ‘snacks are a quest’ elevation.",
    "You’re drifting in the Shroud stream.",
    "You’ve entered: Vibe Corridor B."
  ],
  high: [
    "WHEW. You’re in the clouds with the D4rth Council now.",
    "High-tier elevation: reality is buffering.",
    "You’re so elevated the Shroud asked for your autograph.",
    "You just achieved ‘boss-fight intro’ altitude.",
    "Gravity said ‘I’ll wait.’",
    "You’re airborne like a villain monologue.",
    "This puff has you hearing colors. Respectfully.",
    "You’re floating at ‘plot twist’ level.",
    "The Realm is spinning up the lightning effects.",
    "Your thoughts are doing backflips in 4K.",
    "You’re up there. Like… *up there*.",
    "High elevation: snacks become legendary artifacts.",
    "The Shroud has you on speed dial.",
    "You’re elevated past common sense. Congrats.",
    "This is ‘stare at your hand for 10 minutes’ high.",
    "You’ve entered the Shadow Lounge VIP section.",
    "Your soul just did a barrel roll.",
    "You are now one with the Distortion.",
    "High-tier puff: existence feels like a cutscene.",
    "The Shroud roars: ‘UNLIMITED VIBES.’"
  ]
};
