// economy/workboard-tables.js
// Format: ["Title", "Blurb", [minDD, maxDD]]
// Lore notes: Distortia city, Shroud, Wardens, Chorus, Vault 7, Shadow Market, Luminous Void, Verdant Verge, Hollow Expanse, etc.

export const JOBS = {
  // ====== CITY HUBS ======
  bar: [
    ["Spilled Secrets", "Patron bragged about a Shroud cache. Verify before the booze wears off.", [200, 700]],
    ["Quiet the Crooners", "Karaoke night summoned a chorus demon. De-tune it politely.", [250, 800]],
    ["Rare Ice Run", "Fetch void-chilled ice from the basement crypt-freezer. Try not to get… stuck.", [300, 900]],
    ["VIP Ghost Tab", "Specter at table 7 keeps ordering. Settle an incorporeal bill.", [200, 650]],
    ["Back-Alley Brawl", "Escort staff through the alley. Wardens loitering, vibes rancid.", [400, 1000]],
    ["Counterfeit Coasters", "Someone swapped sigil-coasters with hexed copies. Swap them back.", [180, 600]],
    ["Silent Shaker", "A cursed shaker absorbs sound. Recover it mid-rush.", [220, 650]],
    ["Distorted Sunset", "Recreate the legendary cocktail from a smudged recipe shard.", [300, 900]],
    ["Smuggled Bitters", "Shadow Market bitters delivery went missing. You know where to look.", [350, 1000]],
    ["Barback Blitz", "Three kegs, one spine. Keep the floor alive for an hour.", [150, 550]],
    ["Neon Sign Scream", "Bar sign screams in the Shroud tongue at midnight. Negotiate a ceasefire.", [350, 1000]],
    ["DJ’s Hiss", "Turntable hum is warded. Unbind without silencing the night.", [250, 800]],
    ["Tab of Theseus", "A tab split so many times it became a paradox. Resolve the debt.", [180, 620]],
    ["Glassware Gremlin", "Something chips only rim glasses. Trap and trade it to the Market.", [240, 700]],
    ["Missed Reservation", "VIP’s booking slipped into a pocket of yesterday. Retrieve the slot.", [300, 950]],
    ["Bar Stool Trial", "Stool #4 decides who is worthy. Win the seat for a patron.", [200, 700]],
    ["Spice Raid", "Chef needs Ember-Anise from the Void shelf. It bites.", [260, 820]],
    ["Lost Ring", "Proposal ring fell into the drip tray dimension. Dive responsibly.", [280, 900]],
    ["Tipsy Warden", "Warden off-duty but warding badly. Steer them home sans scandal.", [350, 1100]],
    ["Banshee’s Tab", "Let a banshee scream off-menu safely (and bill appropriately).", [220, 680]],
  ],

  hotel: [
    ["Haunted Turndown", "Pillow mints keep rearranging into runes. Translate & appease.", [400, 1200]],
    ["VIP Wake-Up", "Deliver a wake-up call across a time-slowed corridor.", [250, 900]],
    ["Elevator Oracle", "Lift #3 gives prophecies. Get guests to their floors anyway.", [300, 1000]],
    ["Chef’s Panic", "Banquet needs Shroud-stable soufflé. Source ingredients fast.", [500, 1500]],
    ["Lost Luggage Loop", "Suitcase trapped in a loop between floors 9 and 10. Intercept it.", [250, 800]],
    ["Room 404", "A room that shouldn't exist has guests. De-check them without a scene.", [450, 1400]],
    ["Crystal Concierge", "Concierge gem cracked; it leaks whispers. Patch and rebind.", [350, 1100]],
    ["Pool Gremlin", "Something keeps turning the water carbonated. Un-fizz the pool.", [200, 700]],
    ["Bedding Wards", "Fresh linens repel nightmares. The cart is missing. Find the cart.", [300, 950]],
    ["VIP Corridor", "A director demanded ‘perfect quiet.’ Silence the hall responsibly.", [200, 700]],
    ["Mirror Maze", "A guest multiplied. Gather the correct one with zero lawsuits.", [450, 1300]],
    ["Midnight Pianist", "Piano plays future tunes that spoil films. Retune the keys.", [250, 900]],
    ["Ghosted Suite", "Suite humming with static. Clean without spooking high rollers.", [400, 1200]],
    ["Laundry Knot", "Sheets tied in sailor’s curses. Untie or bribe the curse.", [180, 650]],
    ["Key of Echoes", "Master key developed an attitude. Win it back in song.", [220, 750]],
    ["VIP Shuttle", "Driver vanished mid-route. Finish the pick-up before press arrives.", [350, 1200]],
    ["Bellhop Bargain", "Bell cart accepts offerings now. Satisfy it (cheaply).", [200, 700]],
    ["Security Swap", "Camera feeds swapped with yesterday. Align clocks forward.", [300, 950]],
    ["Check-Out Chase", "Guest checked out of reality. Process refund anyway.", [280, 900]],
    ["Do Not Disturb", "Sign is a contract. Annul without waking the sleeper.", [350, 1300]],
  ],

  casino: [
    ["Cold Table", "Craps table cursed to roll snake eyes. Warm it up ethically.", [700, 2000]],
    ["Drone Hustler", "Bet-drone cheats roulette. Prove it without tipping them off.", [400, 1400]],
    ["VIP Marker", "High-roller’s credit line overdrawn. Secure collateral politely.", [800, 2500]],
    ["Slot Whispers", "Slots whisper stock tips. Mute them before regulators visit.", [500, 1600]],
    ["Dealer’s Hex", "Dealer caught a luck parasite. Extract and comp the shift.", [600, 1800]],
    ["Counter Chip", "Fake kyber-chips entering pit. Trace the source stall.", [500, 1500]],
    ["Eye in the Sky", "Surveillance orbs seeing futures. Re-focus to present.", [450, 1400]],
    ["Croupier Ghost", "Ex-legend dealing from beyond. Secure retirement package.", [600, 1700]],
    ["Wheel Memory", "Roulette remembers winning numbers. Wipe its grudge.", [550, 1600]],
    ["Pit Boss SOS", "Boss’s clipboard is sentient and judgmental. Tame it.", [400, 1200]],
    ["Whale Escort", "High-roller magnet for Wardens. Run a clean route.", [700, 2200]],
    ["Comp Collapse", "Comp system looped infinite buffets. End the feast.", [450, 1300]],
    ["Dice Trial", "Dice demand trial by balance beam. Perform or negotiate.", [500, 1500]],
    ["Duplicate ID", "Two identical whales claim same marker. Detect the mimic.", [650, 1800]],
    ["Dealer Switch", "Hands dealing out of phase. Resync the shift cadence.", [500, 1600]],
    ["Silent Alarm", "An alarm that only winners hear. Locate and disarm.", [450, 1400]],
    ["Credit Wind", "A literal wind steals chips. Bottle it.", [400, 1200]],
    ["Warden Audit", "Wardens inspecting rituals. Make everything… normal.", [800, 2200]],
    ["Luck Vacuum", "Table 6 drains luck. Feed it decoy fortune.", [600, 1700]],
    ["Backroom Bridge", "Bridge to yesterday opened in count room. Close it fast.", [900, 2500]],
  ],

  market: [
    ["Hot Cargo", "Crate might implode morale (and wall). Decide its fate.", [500, 1500]],
    ["Debt Whisper", "Broker vs. client standoff. Mediate without blades.", [250, 900]],
    ["Counterfeit Sweep", "Fake kyber-wire among stalls. Swap the reels.", [600, 2000]],
    ["Map of Else", "A map keeps redrawing routes to ‘Else.’ Pin it down.", [300, 1000]],
    ["Vendor Feud", "Two spice dealers curse each other’s stock. Broker peace.", [350, 1100]],
    ["Silent Auction", "Auctioneer lost their voice to a pact. Retrieve it.", [400, 1200]],
    ["Lost Permit", "Permit eaten by a paper wyrm. Track it through forms.", [250, 800]],
    ["Gremlin Bait", "Catch shelf-gremlins sabotaging displays, resell them humanely.", [300, 950]],
    ["Price Mirage", "Prices shift by observer. Stabilize a baseline.", [450, 1400]],
    ["Smuggler Trail", "Follow citrus-peel sigils to a hidden stall.", [400, 1200]],
    ["Echoed Trade", "A deal echoes twice with different terms. Pick the right one.", [350, 1100]],
    ["Tiller Tangle", "Cart tiller knot is a binding spell. Untie cleanly.", [250, 900]],
    ["Haggle Demon", "A demon loves negotiating. Beat it at its own game.", [500, 1500]],
    ["Mirror Fruits", "Fruit reflects eater’s mood. Arrange for smiles.", [300, 1000]],
    ["Vanishing Stall", "Your target stall vanishes hourly. Wait or bait?", [400, 1200]],
    ["Ward Tokens", "Tokens imprint buyer’s debts. Scrub the residue.", [450, 1300]],
    ["Scent Thief", "Perfumer’s scents stolen by breeze sprites. Net them.", [250, 900]],
    ["Shadow Auction", "Underground lot: shut down without angering everyone.", [700, 2000]],
    ["Paperwork Hydra", "Permit form spawns two more. Slay with staplers.", [300, 900]],
    ["Smile Tax", "Gate guard charges smiles. Find the loophole.", [200, 800]],
  ],

  vault: [
    ["Phantom Alarm", "Ghost signal keeps tripping Vault 7. Trace and purge.", [700, 1800]],
    ["Identity Spoof", "Client’s prints cloned. Identify the tap.", [900, 2200]],
    ["Armored Route", "Escort emergency transfer through Market zones.", [1000, 3000]],
    ["Key Choir", "Keys sing in dissonance; open nothing. Reharmonize.", [600, 1600]],
    ["Ledger Ghost", "A number refuses to balance. Negotiate with it.", [650, 1700]],
    ["Silent Footfalls", "Hall swallows sound (and guards). Restore echoes.", [500, 1500]],
    ["Box 13", "Box claims ownership of client. Reassign politely.", [700, 1800]],
    ["Ward Drift", "Wards drift off the walls at night. Pin them back.", [600, 1600]],
    ["Ink Trial", "Contract ink crawls. Trap it on signature lines.", [500, 1500]],
    ["Schedule Knot", "Appointment spiral forms a knot. Untangle time.", [650, 1750]],
    ["Loan of Names", "Names borrowed against interest. Collect without erasing.", [800, 2200]],
    ["Specter Teller", "Ghost teller helps and hinders. Set boundaries.", [500, 1400]],
    ["Split Vault", "Vault inside a vault keeps nesting. Close the loop.", [900, 2500]],
    ["Credit Echo", "Transactions echo a day later. Silence the reverb.", [600, 1600]],
    ["Paper Storm", "Archive rebels into a cyclone. Calm the stacks.", [450, 1300]],
    ["Chain of Custody", "Chain literally grew. Resize the links.", [700, 1800]],
    ["Warden Lien", "Wardens placed a lien on reality. Appeal it.", [800, 2000]],
    ["Shadow Deposit", "Shadow tried to open an account. Deny compassionately.", [650, 1700]],
    ["Overnight Audit", "Audit from the Chorus at dawn. Make it normal.", [900, 2300]],
    ["Locksmith Duel", "Locks challenge you to riddles. Win three.", [600, 1600]],
  ],

  // ====== SIDE QUESTS (50) ======
  side: [
    ["Lost Kid in Fog", "Child wandered into Shroud pockets near the riverwalk.", [200, 600]],
    ["Beacon Repair", "Broken relay stalls rescue ops on the causeway.", [350, 1200]],
    ["Warden Shakedown", "Rogue patrol extorting travelers. Intervene cleanly.", [800, 2000]],
    ["Courier Chase", "Intercept a mimic courier before it replicates invoices.", [300, 900]],
    ["Street Choir", "Unlicensed chorus summons rain. Permit or placate.", [250, 800]],
    ["Runaway Ad", "A sentient ad won’t stop following a tourist.", [200, 700]],
    ["Bridge of Echoes", "Bridge repeats yesterday’s arguments. Reset it.", [350, 1000]],
    ["Stray Familiar", "A cat that’s not a cat keeps opening cupboards.", [200, 700]],
    ["Skyhook Jam", "Skyhook stuck with VIP crate mid-air. Reel it in.", [400, 1200]],
    ["Map to Lunch", "Map only points to sandwiches. Decode its hunger.", [150, 600]],
    ["Laughter Tax", "District charges laughs. Audit the collector.", [250, 900]],
    ["Shadow Tag", "Kids play tag with actual shadows. End the game.", [200, 750]],
    ["Dream Broker", "Broker selling pre-slept dreams. Regulate or rescue.", [450, 1300]],
    ["Borrowed Shoes", "Shoes walked off wearing a man. Fetch him back.", [250, 800]],
    ["Echoed Bill", "Every payment doubles in echo. Cap the reverb.", [300, 950]],
    ["Stray Drone", "Delivery drone nests in the clocktower. Relocate.", [220, 700]],
    ["Runaway Tram", "Tram refuses to stop, claims it’s ‘free.’ Negotiate.", [400, 1100]],
    ["Fountain Coin", "Wish coins unionized. Bargain a contract.", [250, 800]],
    ["Street Painter", "Murals come alive at dusk. Curate responsibly.", [300, 950]],
    ["Lost Tune", "A whistled tune can’t find its owner. Track by rhythm.", [200, 700]],
    ["Cracked Hour", "Hourglass cracked; 15 minutes went missing. Find them.", [350, 1000]],
    ["Chess in Rain", "A match that never ends. Declare a dignified draw.", [200, 700]],
    ["Shroud Bloom", "A flower opens portals when watered. Choose wisely.", [500, 1500]],
    ["Bottle Message", "Note argues with reader. Mediate the message.", [200, 700]],
    ["Night Market Fox", "Fox sells fake moonlight. Expose or partner up.", [350, 1200]],
    ["Badge Swap", "Two inspectors swapped badges and destinies. Swap back.", [250, 900]],
    ["Riddle Cart", "Vendor only accepts answers. Pay in wit.", [200, 700]],
    ["Lantern’s Debt", "A lantern owes light to the river. Repay it.", [250, 850]],
    ["Umbrella Duet", "Two umbrellas in love block the street. Stage a finale.", [150, 600]],
    ["Clock Hand", "A clock hand filed for leave. Cover the shift.", [200, 700]],
    ["Paper Sail", "Letter folded into a boat fled to sea. Catch it.", [250, 850]],
    ["Window Swap", "Two apartments swapped views. Unswitch without notice.", [300, 950]],
    ["Chorus Seed", "Seed hums in chorus key. Plant where it belongs.", [400, 1200]],
    ["Borrowed Shadow", "A shadow wants its person back by midnight.", [350, 1000]],
    ["Step Tax", "Stairs charge per step. Negotiate a bulk rate.", [150, 650]],
    ["Moon Stain", "Moonlight stained a dress. Bleach with starlight.", [250, 900]],
    ["Whistle Stop", "Guard whistle started a rave. End it kindly.", [300, 950]],
    ["Tin Hero", "Toy soldier leads gutter troops. Promote or retire.", [200, 700]],
    ["Busker Duel", "Two lute gods in a feud. Declare harmony.", [250, 850]],
    ["Mirror Ticket", "Ticket reflects a better seat. Upgrade fate.", [200, 700]],
    ["Warden’s Cat", "Cat steals insignias. Return them (keep scratches).", [250, 900]],
    ["Ghost Queue", "Line of ghosts waiting for nothing. Dismiss them.", [300, 1000]],
    ["Fog Librarian", "Fog wants to read; guide it through a book.", [200, 700]],
    ["Baker’s Moon", "Bread rises with tides. Schedule the bake.", [250, 900]],
    ["Boat of Keys", "Boat made of keys docks tonight. Pick the right one.", [350, 1200]],
    ["Stolen Yawn", "Someone stole the city’s yawn. Find the culprit.", [200, 700]],
    ["Shoe Eclipse", "Two shoes eclipse every dusk. Stage a reunion.", [200, 700]],
    ["Wall’s Ear", "Wall overheard a crime. Take its testimony.", [400, 1200]],
    ["Night Post", "Mail arrives at midnight from tomorrow. Sort gently.", [300, 1000]],
    ["Glitch Vendor", "Vendor glitches items in and out. Stabilize stock.", [350, 1100]],
    ["Kindness Heist", "Steal back kindness hoarded in a vault of pride.", [600, 1600]],
  ],

  // ====== REGIONS ======
  he: [ // Hollow Expanse (15)
    ["Wind Bones", "Collect wind-bones from exposed dunes for a ritual.", [500, 1400]],
    ["Salt Choir", "Salt pillars sing; map their notes before sunset.", [450, 1200]],
    ["Glass Crawl", "Crawl under glass dunes to free trapped caravans.", [700, 1800]],
    ["Echo Dowsing", "Find water echoes with a broken forked rod.", [500, 1500]],
    ["Dune Warden", "A Warden patrol stranded. Extract without flares.", [800, 2000]],
    ["Bone Ledger", "Scavenge caravan ledgers guarded by beetle swarms.", [600, 1700]],
    ["Silt Sleepers", "Wake buried travelers before the night freeze.", [550, 1500]],
    ["Sand Mirror", "A mirror shows routes not taken. Choose one.", [500, 1300]],
    ["Cactus Milk", "Harvest safe cactus milk; avoid the laughing kind.", [400, 1200]],
    ["Hollow Drum", "A drum made of wind summons a guide. Play true.", [500, 1400]],
    ["Dust Treaty", "Broker peace between dust sprites and miners.", [600, 1600]],
    ["Worm Sign", "Ride out a harmless worm tremor; protect the camp.", [700, 1800]],
    ["Nomad Marker", "Restore erased waystones before a storm.", [550, 1400]],
    ["Shard Shade", "Collect shard-shade for travelers’ shelters.", [400, 1100]],
    ["Moon Compass", "Align a moon compass with star bones.", [650, 1700]],
  ],

  vv: [ // Verdant Verge (15)
    ["Root Bridge", "Living bridge sulks; coax it to carry pilgrims.", [450, 1200]],
    ["Bloom Fever", "Pacify pollen spirits causing fevers.", [500, 1400]],
    ["Thorn Accord", "Broker truce with a thorn hedge brigade.", [550, 1500]],
    ["Moss Relay", "Re-grow moss relays to restore forest calling.", [500, 1300]],
    ["Grove Trial", "Pass the grove’s riddle; free a trapped ranger.", [600, 1600]],
    ["Petal Scouts", "Escort petal-scouts mapping clearings.", [400, 1200]],
    ["Sap Thief", "Catch a sap siphon draining elder trees.", [500, 1400]],
    ["Stag Crown", "Return a crown to the antler king. Bow properly.", [650, 1700]],
    ["Spore Map", "Translate spore constellations into a safe path.", [550, 1500]],
    ["Fae Toll", "Pay the toll in stories—find the best one.", [400, 1200]],
    ["Lantern Vines", "Untangle light-vines choking a bridge.", [450, 1300]],
    ["Brook Bargain", "Rogue brook wants a name; gift it one.", [500, 1400]],
    ["Nectar Pact", "Negotiate nectar shares with giant bees.", [600, 1600]],
    ["Leaf Armor", "Weave leaf-armor for a scared child.", [350, 1100]],
    ["Echo Orchard", "Fruit repeats secrets; harvest discreetly.", [500, 1400]],
  ],

  lv: [ // Luminous Void (15)
    ["Light Anchor", "Anchor a stray light-island drifting toward town.", [700, 1800]],
    ["Star Silt", "Collect star silt before it sublimates.", [600, 1600]],
    ["Aether Leak", "Plug a leak shimmering above Dock 3.", [800, 2000]],
    ["Glow Thief", "Catch a glow-thief dimming the district.", [500, 1500]],
    ["Void Choir", "Calm a choir of lights mimicking alarms.", [650, 1700]],
    ["Mirror Swim", "Swim a mirrored channel; bring back a reflection.", [700, 1800]],
    ["Prism Cart", "Escort a prism cart through glare storms.", [600, 1600]],
    ["Shadow Tax", "Shadows charge rent; audit their books.", [500, 1500]],
    ["Lumen Lattice", "Repair the light lattice above Old Harbor.", [700, 1800]],
    ["Mote Rescue", "Rescue a mote school from a gravity eddy.", [550, 1500]],
    ["Glimmer Forge", "Restart a forge that burns twilight.", [800, 2000]],
    ["Neon Treaty", "Broker peace between rival neon bands.", [600, 1600]],
    ["Aurora Riddle", "Solve an aurora’s riddle; win safe passage.", [700, 1800]],
    ["Lenskeeper", "A lenskeeper lost her glasses (of power). Find them.", [500, 1400]],
    ["Night Ferry", "Guide the last ferry across a lightless patch.", [650, 1700]],
  ],
};
