// origins.js
export const ORIGINS = [
  { planet: "Earth", state: "Alabama",    city: "Birmingham" },
  { planet: "Earth", state: "Alaska",     city: "Anchorage" },
  { planet: "Earth", state: "Arizona",    city: "Phoenix" },
  { planet: "Earth", state: "Arkansas",   city: "Little Rock" },
  { planet: "Earth", state: "California", city: "Los Angeles" },
  { planet: "Earth", state: "Colorado",   city: "Denver" },
  { planet: "Earth", state: "Connecticut",city: "Bridgeport" },
  { planet: "Earth", state: "Delaware",   city: "Wilmington" },
  { planet: "Earth", state: "Florida",    city: "Miami" },
  { planet: "Earth", state: "Georgia",    city: "Atlanta" },
  { planet: "Earth", state: "Hawaii",     city: "Honolulu" },
  { planet: "Earth", state: "Idaho",      city: "Boise" },
  { planet: "Earth", state: "Illinois",   city: "Chicago" },
  { planet: "Earth", state: "Indiana",    city: "Indianapolis" },
  { planet: "Earth", state: "Iowa",       city: "Des Moines" },
  { planet: "Earth", state: "Kansas",     city: "Wichita" },
  { planet: "Earth", state: "Kentucky",   city: "Louisville" },
  { planet: "Earth", state: "Louisiana",  city: "New Orleans" },
  { planet: "Earth", state: "Maine",      city: "Portland" },
  { planet: "Earth", state: "Maryland",   city: "Baltimore" },
  { planet: "Earth", state: "Massachusetts", city: "Boston" },
  { planet: "Earth", state: "Michigan",   city: "Detroit" },
  { planet: "Earth", state: "Minnesota",  city: "Minneapolis" },
  { planet: "Earth", state: "Mississippi", city: "Jackson" },
  { planet: "Earth", state: "Missouri",   city: "Kansas City" },
  { planet: "Earth", state: "Montana",    city: "Billings" },
  { planet: "Earth", state: "Nebraska",   city: "Omaha" },
  { planet: "Earth", state: "Nevada",     city: "Las Vegas" },
  { planet: "Earth", state: "New Hampshire", city: "Manchester" },
  { planet: "Earth", state: "New Jersey", city: "New ark" },
  { planet: "Earth", state: "New Mexico", city: "Albuquerque" },
  { planet: "Earth", state: "New York",   city: "New York City" },
  { planet: "Earth", state: "North Carolina", city: "Charlotte" },
  { planet: "Earth", state: "North Dakota", city: "Fargo" },
  { planet: "Earth", state: "Ohio",       city: "Columbus" },
  { planet: "Earth", state: "Oklahoma",   city: "Oklahoma City" },
  { planet: "Earth", state: "Oregon",     city: "Portland" },
  { planet: "Earth", state: "Pennsylvania", city: "Philadelphia" },
  { planet: "Earth", state: "Rhode Island", city: "Providence" },
  { planet: "Earth", state: "South Carolina", city: "Charleston" },
  { planet: "Earth", state: "South Dakota", city: "Sioux Falls" },
  { planet: "Earth", state: "Tennessee",  city: "Memphis" },
  { planet: "Earth", state: "Texas",      city: "Houston" },
  { planet: "Earth", state: "Utah",       city: "Salt Lake City" },
  { planet: "Earth", state: "Vermont",    city: "Burlington" },
  { planet: "Earth", state: "Virginia",   city: "Richmond" },
  { planet: "Earth", state: "Washington", city: "Seattle" },
  { planet: "Earth", state: "West Virginia", city: "Charleston" },
  { planet: "Earth", state: "Wisconsin",  city: "Milwaukee" },
  { planet: "Earth", state: "Wyoming",    city: "Cheyenne" },

  // === KORRIBAN-LIKE ===
  { planet: "Distortia", region: "Valley of Echoes" },
  { planet: "Distortia", region: "Obsidian Wastes" },
  { planet: "Distortia", region: "The Bleeding Mesa" },
  { planet: "Distortia", region: "Tombspire Canyon" },
  { planet: "Distortia", region: "Red Ash Sanctuary" },

  // === CORELIA-LIKE ===
  { planet: "Crimeria", region: "Shipwright Quarter" },
  { planet: "Crimeria", region: "Starlance Docks" },
  { planet: "Crimeria", region: "Ion Row Industrial Zone" },
  { planet: "Crimeria", region: "Skyforge Sprawl" },
  { planet: "Crimeria", region: "Ridgeport Outskirts" },

  // === MARS ANNEX ===
  { planet: "Mars Annex", region: "Cinder Rim" },
  { planet: "Mars Annex", region: "The Iron Scar" },
  { planet: "Mars Annex", region: "Helion Crater" },
  { planet: "Mars Annex", region: "Duskspire Colony" },
  { planet: "Mars Annex", region: "Ashpoint Refuge" },

  // === EUROPA FREEPORT ===
  { planet: "Europa Freeport", region: "Ice Bazaar" },
  { planet: "Europa Freeport", region: "Crystalline Ward" },
  { planet: "Europa Freeport", region: "Frostline Market" },
  { planet: "Europa Freeport", region: "The Hollow Reaches" },
  { planet: "Europa Freeport", region: "Driftspire Hub" }
  
];
